const $=id=>document.getElementById(id);
const STORE='kwater_v7_records', USERS='kwater_v7_users', NOTICES='kwater_v7_notices', GKEY='kwater_google_key_v7';
let records=JSON.parse(localStorage.getItem(STORE)||'[]'), users=JSON.parse(localStorage.getItem(USERS)||'[]'), notices=JSON.parse(localStorage.getItem(NOTICES)||'[]');
let currentUser=null, editId=null, charts={}, googleMap=null, geocoder=null, markers=[];
const uid=()=>Date.now().toString(36)+Math.random().toString(36).slice(2,8); const today=()=>new Date().toISOString().slice(0,10); const yr=d=>new Date(d).getFullYear(); const qtr=d=>Math.ceil((new Date(d).getMonth()+1)/3);
function saveAll(){localStorage.setItem(STORE,JSON.stringify(records));localStorage.setItem(USERS,JSON.stringify(users));localStorage.setItem(NOTICES,JSON.stringify(notices));}
function initData(){if(!users.length) users=[{id:'admin',pw:'1234',name:'관리자',role:'admin',approved:true},{id:'user',pw:'1234',name:'일반사용자',role:'user',approved:true}]; if(!notices.length) notices=[{id:uid(),title:'전기방식 정기점검 안내',body:'분기별 TB 측정자료를 등록해 주세요.',date:today(),author:'관리자'},{id:uid(),title:'측정기 교정 주기 안내',body:'기준 장비의 교정 유효기간을 확인해 주세요.',date:today(),author:'관리자'},{id:uid(),title:'여름철 부식관리 요령',body:'우천 후 Test Box 내부 침수 여부를 확인해 주세요.',date:today(),author:'관리자'}]; if(!records.length){const y=new Date().getFullYear();[['TB-001','시흥정수장','침전지 1계열','경기도 시흥시 정왕동 침전지 북측','정류기-1',-965],['TB-002','반월정수장','정문 앞 관로','경기도 안산시 단원구 반월정수장 정문 앞','정류기-2',-830],['TB-003','안양가압장','배출관로','경기도 안양시 동안구 가압장 배출관로','정류기-3',-780],['TB-004','광명가압장','펜스 옆','경기도 광명시 가압장 펜스 옆','정류기-4',-1010]].forEach((b,i)=>{for(let yy=y-2;yy<=y;yy++)for(let q=1;q<=4;q++)records.push({id:uid(),date:`${yy}-${String(q*3-1).padStart(2,'0')}-20`,tbName:b[0],site:b[1],facility:b[2],address:b[3],rectifier:b[4],onPotential:b[5]-70+q*5,offPotential:b[5]+(yy-y)*15+q*6,memo:'샘플 데이터',photo:''});});} saveAll();}
function st(v){v=Number(v); if(v<=-850)return{key:'good',txt:'양호'}; if(v<=-800)return{key:'warn',txt:'점검필요'}; return{key:'bad',txt:'긴급조치'};} function badge(v){const s=st(v);return `<span class="badge ${s.key}">${s.txt}</span>`;} function latest(){let m={};records.slice().sort((a,b)=>a.date.localeCompare(b.date)).forEach(r=>m[r.tbName]=r);return Object.values(m);} function pct(n,t){return t?((n/t)*100).toFixed(1)+'%':'0%';}
function setClock(){const d=new Date(),yo='일월화수목금토'[d.getDay()];$('clock').textContent=`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}(${yo}) ${String(d.getHours()).padStart(2,'0')}:${String(d.getMinutes()).padStart(2,'0')}`;}
function login(){const id=$('loginId').value.trim(), pw=$('loginPw').value; const u=users.find(x=>x.id===id&&x.pw===pw); if(!u)return alert('아이디 또는 비밀번호를 확인하세요.'); if(!u.approved)return alert('관리자 승인 대기 중입니다.'); currentUser=u; $('login').classList.add('hidden'); $('app').classList.remove('hidden'); document.querySelectorAll('.adminOnly').forEach(e=>e.style.display=u.role==='admin'?'':'none'); renderAll();}
function view(id){document.querySelectorAll('.view').forEach(v=>v.classList.remove('active')); $(id).classList.add('active'); document.querySelectorAll('.nav').forEach(n=>n.classList.toggle('active',n.dataset.view===id)); const titles={dash:'대시보드',tb:'TB 관리',entry:'측정 입력',history:'3개년 이력',graph:'그래프 분석',map:'Google GIS 지도',notice:'공지사항',members:'회원관리',settings:'설정'}; $('pageTitle').textContent=titles[id]||'대시보드'; if(id==='history')drawHistory(); if(id==='graph')drawGraph(); if(id==='map')renderMap(); if(id==='notice')renderNotices(); if(id==='members')renderMembers();}
function renderSummary(){const l=latest(), t=l.length, g=l.filter(r=>st(r.offPotential).key==='good').length, w=l.filter(r=>st(r.offPotential).key==='warn').length, b=l.filter(r=>st(r.offPotential).key==='bad').length; $('totalTb').textContent=t; $('goodCnt').textContent=g; $('warnCnt').textContent=w; $('badCnt').textContent=b; $('goodPct').textContent=pct(g,t); $('warnPct').textContent=pct(w,t); $('badPct').textContent=pct(b,t);}
function renderFakeMap(id='dashMap'){const el=$(id); if(!el)return; el.innerHTML=''; latest().forEach((r,i)=>{const p=document.createElement('div');p.className='pin '+st(r.offPotential).key;p.textContent=r.tbName;p.style.left=(18+(i*19)%68)+'%';p.style.top=(22+(i*23)%58)+'%';el.appendChild(p);});}
function renderRecent(){$('recentList').innerHTML=latest().sort((a,b)=>b.date.localeCompare(a.date)).slice(0,6).map(r=>`<div class="recentItem"><div><b>${r.tbName}</b><br><small>${r.site} · ${r.facility}<br>${r.address||''}</small></div><div>${badge(r.offPotential)}<br><small>${r.offPotential}mV</small></div></div>`).join('');}
function renderDashNotice(){$('dashNotice').innerHTML=notices.slice().reverse().slice(0,4).map(n=>`<li><b>${n.title}</b><br><span>${n.date}</span></li>`).join('');}
function renderTable(){const q=($('search')?.value||'').toLowerCase(); const rows=records.slice().sort((a,b)=>b.date.localeCompare(a.date)).filter(r=>!q||[r.tbName,r.site,r.facility,r.address,r.rectifier].join(' ').toLowerCase().includes(q)); $('dataTable').innerHTML='<thead><tr><th>측정일</th><th>분기</th><th>TB명</th><th>사업소</th><th>시설명</th><th>위치/주소</th><th>OFF</th><th>상태</th><th>관리</th></tr></thead><tbody>'+rows.map(r=>`<tr><td>${r.date}</td><td>${yr(r.date)}년 ${qtr(r.date)}Q</td><td><b>${r.tbName}</b></td><td>${r.site||''}</td><td>${r.facility||''}</td><td>${r.address||''}</td><td>${r.offPotential}</td><td>${badge(r.offPotential)}</td><td><button class="whiteBtn" onclick="editRec('${r.id}')">수정</button> <button class="redBtn" onclick="delRec('${r.id}')">삭제</button></td></tr>`).join('')+'</tbody>';}
function fileURL(f){return new Promise(res=>{if(!f)return res(''); const fr=new FileReader(); fr.onload=()=>res(fr.result); fr.readAsDataURL(f);});}
async function saveRec(){const old=records.find(r=>r.id===editId), f=$('photo').files[0]; const rec={id:editId||uid(),date:$('date').value||today(),tbName:$('tbName').value.trim(),site:$('site').value.trim(),facility:$('facility').value.trim(),address:$('address').value.trim(),rectifier:$('rectifier').value.trim(),onPotential:$('onPotential').value,offPotential:$('offPotential').value,memo:$('memo').value.trim(),photo:f?await fileURL(f):(old?.photo||'')}; if(!rec.tbName)return alert('TB명을 입력하세요.'); if(editId)records=records.map(r=>r.id===editId?rec:r); else records.push(rec); saveAll(); clearForm(); renderAll(); view('tb');}
function editRec(id){const r=records.find(x=>x.id===id); if(!r)return; editId=id; $('formTitle').textContent='측정 데이터 수정'; ['date','tbName','site','facility','address','rectifier','onPotential','offPotential','memo'].forEach(k=>$(k).value=r[k]||''); view('entry');}
function delRec(id){if(confirm('삭제할까요?')){records=records.filter(r=>r.id!==id);saveAll();renderAll();}}
function clearForm(){editId=null;$('formTitle').textContent='측정 데이터 등록';['tbName','site','facility','address','rectifier','onPotential','offPotential','memo'].forEach(k=>$(k).value='');$('date').value=today();$('photo').value='';}
function fillSelect(id){$(id).innerHTML=[...new Set(records.map(r=>r.tbName))].sort().map(t=>`<option>${t}</option>`).join('');}
function drawDashCharts(){const y=new Date().getFullYear(), labels=[],good=[],warn=[],bad=[]; for(let yy=y-2;yy<=y;yy++)for(let q=1;q<=4;q++){labels.push(`${yy} ${q}Q`); const arr=records.filter(r=>yr(r.date)===yy&&qtr(r.date)===q); good.push(arr.filter(r=>st(r.offPotential).key==='good').length);warn.push(arr.filter(r=>st(r.offPotential).key==='warn').length);bad.push(arr.filter(r=>st(r.offPotential).key==='bad').length);} if(charts.bar)charts.bar.destroy(); charts.bar=new Chart($('barChart'),{type:'bar',data:{labels,datasets:[{label:'양호',data:good,backgroundColor:'#18a765'},{label:'점검필요',data:warn,backgroundColor:'#f59e0b'},{label:'긴급조치',data:bad,backgroundColor:'#ef4444'}]},options:{responsive:true,maintainAspectRatio:false,scales:{x:{stacked:true},y:{stacked:true,beginAtZero:true}}}}); const tb=latest()[0]?.tbName||''; $('trendTbName').textContent=tb?`(${tb})`:''; const arr=records.filter(r=>r.tbName===tb).sort((a,b)=>a.date.localeCompare(b.date)).slice(-12); if(charts.line)charts.line.destroy(); charts.line=new Chart($('lineChart'),{type:'line',data:{labels:arr.map(r=>r.date),datasets:[{label:'OFF',data:arr.map(r=>r.offPotential),borderColor:'#18a765',backgroundColor:'#18a765',tension:.25},{label:'-850mV 기준',data:arr.map(()=>-850),borderColor:'#ef4444',borderDash:[6,6],pointRadius:0}]},options:{responsive:true,maintainAspectRatio:false}});}
function drawHistory(){fillSelect('historyTb'); const tb=$('historyTb').value, y=new Date().getFullYear(), years=[y-2,y-1,y], vals={}; years.forEach(yy=>vals[yy]=[null,null,null,null]); records.filter(r=>r.tbName===tb).forEach(r=>{if(vals[yr(r.date)])vals[yr(r.date)][qtr(r.date)-1]=Number(r.offPotential)}); $('quarterTable').innerHTML='<thead><tr><th>년도</th><th>1Q</th><th>2Q</th><th>3Q</th><th>4Q</th></tr></thead><tbody>'+years.map(yy=>`<tr><td><b>${yy}</b></td>${vals[yy].map(v=>`<td>${v===null?'-':v+' mV'}</td>`).join('')}</tr>`).join('')+'</tbody>'; const labels=[],data=[]; years.forEach(yy=>[1,2,3,4].forEach((q,i)=>{labels.push(`${yy} ${q}Q`);data.push(vals[yy][i])})); if(charts.history)charts.history.destroy(); charts.history=new Chart($('historyChart'),{type:'line',data:{labels,datasets:[{label:'OFF 전위',data,borderColor:'#0b72d9',backgroundColor:'#0b72d9',tension:.25},{label:'-850 기준',data:labels.map(()=>-850),borderColor:'#ef4444',borderDash:[6,6],pointRadius:0}]},options:{responsive:true,maintainAspectRatio:false}});}
function drawGraph(){fillSelect('graphTb'); const tb=$('graphTb').value, arr=records.filter(r=>r.tbName===tb).sort((a,b)=>a.date.localeCompare(b.date)); if(charts.graph)charts.graph.destroy(); charts.graph=new Chart($('graphChart'),{type:'line',data:{labels:arr.map(r=>r.date),datasets:[{label:'ON',data:arr.map(r=>r.onPotential),borderColor:'#0b72d9',backgroundColor:'#0b72d9',tension:.25},{label:'OFF',data:arr.map(r=>r.offPotential),borderColor:'#18a765',backgroundColor:'#18a765',tension:.25},{label:'-850 기준',data:arr.map(()=>-850),borderColor:'#ef4444',borderDash:[6,6],pointRadius:0}]},options:{responsive:true,maintainAspectRatio:false}});}
function loadGoogle(key){return new Promise((ok,no)=>{if(window.google?.maps)return ok(); window.initGoogleMap=ok; const s=document.createElement('script'); s.src=`https://maps.googleapis.com/maps/api/js?key=${key}&callback=initGoogleMap`; s.async=true; s.onerror=no; document.head.appendChild(s);});}
async function renderMap(){renderFakeMap('fallbackMap'); const key=localStorage.getItem(GKEY)||$('googleKey').value.trim(); $('googleKey').value=key; if(!key){$('mapNotice').textContent='Google Maps API Key를 입력하면 실제 지도와 주소 기반 위치 표시가 됩니다.'; return;} try{await loadGoogle(key); $('fallbackMap').style.display='none'; $('mapNotice').textContent='Google Maps 연동 완료. 주소를 지오코딩하여 마커를 표시합니다.'; googleMap=new google.maps.Map($('googleMap'),{center:{lat:37.4,lng:126.9},zoom:12,mapTypeId:'satellite'}); geocoder=new google.maps.Geocoder(); markers.forEach(m=>m.setMap(null)); markers=[]; latest().forEach((r,i)=>{const addr=r.address||`${r.site} ${r.facility}`; geocoder.geocode({address:addr},(res,status)=>{if(status==='OK'&&res[0]){const s=st(r.offPotential), color=s.key==='good'?'#18a765':s.key==='warn'?'#f59e0b':'#ef4444'; const marker=new google.maps.Marker({map:googleMap,position:res[0].geometry.location,title:r.tbName,label:{text:r.tbName,color:'#fff',fontWeight:'bold'},icon:{path:google.maps.SymbolPath.CIRCLE,scale:16,fillColor:color,fillOpacity:1,strokeWeight:2,strokeColor:'#fff'}}); const info=new google.maps.InfoWindow({content:`<div class="gmInfo"><b>${r.tbName}</b><br>${r.site} / ${r.facility}<br>${r.address}<hr>측정일: ${r.date}<br>ON: ${r.onPotential}mV<br>OFF: ${r.offPotential}mV<br>상태: ${s.txt}</div>`}); marker.addListener('click',()=>info.open(googleMap,marker)); markers.push(marker); if(i===0)googleMap.setCenter(res[0].geometry.location);}});});}catch(e){$('fallbackMap').style.display='block'; $('mapNotice').textContent='지도 로딩 실패: Google Maps API Key, Maps JavaScript API 활성화, 도메인 제한 설정을 확인하세요.';}}
function renderNotices(){renderDashNotice(); $('noticeList').innerHTML=notices.slice().reverse().map(n=>`<div class="noticeCard"><h4>${n.title}</h4><div class="noticeMeta">${n.date} · ${n.author}</div><p>${(n.body||'').replaceAll('\n','<br>')}</p>${currentUser?.role==='admin'?`<button class="redBtn" onclick="delNotice('${n.id}')">삭제</button>`:''}</div>`).join('');}
function delNotice(id){if(confirm('공지사항을 삭제할까요?')){notices=notices.filter(n=>n.id!==id);saveAll();renderNotices();}}
function saveNotice(){const title=$('noticeTitle').value.trim(), body=$('noticeBody').value.trim(); if(!title)return alert('제목을 입력하세요.'); notices.push({id:uid(),title,body,date:today(),author:currentUser.name}); $('noticeTitle').value=''; $('noticeBody').value=''; $('noticeForm').classList.add('hidden'); saveAll(); renderNotices();}
function renderMembers(){$('memberTable').innerHTML='<thead><tr><th>아이디</th><th>이름</th><th>권한</th><th>상태</th><th>관리</th></tr></thead><tbody>'+users.map(u=>`<tr><td>${u.id}</td><td>${u.name}</td><td>${u.role}</td><td>${u.approved?'승인':'승인대기'}</td><td>${u.id==='admin'?'-':`${!u.approved?`<button class="blueBtn" onclick="approveUser('${u.id}')">승인</button>`:''} <button class="redBtn" onclick="rejectUser('${u.id}')">삭제</button>`}</td></tr>`).join('')+'</tbody>';}
function approveUser(id){const u=users.find(x=>x.id===id); if(u){u.approved=true;saveAll();renderMembers();}} function rejectUser(id){if(confirm('삭제할까요?')){users=users.filter(u=>u.id!==id);saveAll();renderMembers();}}
function join(){const id=$('joinId').value.trim(), name=$('joinName').value.trim(), pw=$('joinPw').value; if(!id||!name||!pw)return alert('모두 입력하세요.'); if(users.some(u=>u.id===id))return alert('이미 있는 아이디입니다.'); users.push({id,pw,name,role:'user',approved:false}); saveAll(); $('joinModal').classList.add('hidden'); alert('회원가입 신청 완료. 관리자 승인 후 로그인 가능합니다.');}
function exportExcel(){const rows=records.map(r=>({측정일:r.date,분기:`${yr(r.date)}년 ${qtr(r.date)}Q`,TB명:r.tbName,사업소:r.site,시설명:r.facility,위치주소:r.address,정류기명:r.rectifier,ON전위:r.onPotential,OFF전위:r.offPotential,상태:st(r.offPotential).txt,비고:r.memo})); const ws=XLSX.utils.json_to_sheet(rows), wb=XLSX.utils.book_new(); XLSX.utils.book_append_sheet(wb,ws,'전기방식관리대장'); XLSX.writeFile(wb,`K-water_Tech_전기방식_${today()}.xlsx`);}
function renderAll(){renderSummary();renderFakeMap();renderRecent();renderDashNotice();renderTable();drawDashCharts();fillSelect('historyTb');fillSelect('graphTb');}
document.addEventListener('DOMContentLoaded',()=>{initData();setClock();setInterval(setClock,30000);$('date').value=today();$('googleKey').value=localStorage.getItem(GKEY)||'';$('loginBtn').onclick=login;$('logoutBtn').onclick=()=>{
    currentUser = null;

    $('app').classList.add('hidden');
    $('login').classList.remove('hidden');

    $('loginId').value='';
    $('loginPw').value='';
};$('joinOpen').onclick=()=>$('joinModal').classList.remove('hidden');$('joinClose').onclick=()=>$('joinModal').classList.add('hidden');$('joinSubmit').onclick=join;$('saveBtn').onclick=saveRec;$('clearBtn').onclick=clearForm;if($('sampleBtn')){
    $('sampleBtn').onclick=()=>{
        records=[];
        saveAll();
        initData();
        renderAll();
    };
}$('exportBtn').onclick=exportExcel;$('search').oninput=renderTable;$('historyTb').onchange=drawHistory;$('graphTb').onchange=drawGraph;$('saveKey').onclick=()=>{localStorage.setItem(GKEY,$('googleKey').value.trim());renderMap();};$('noticeWriteBtn').onclick=()=>$('noticeForm').classList.remove('hidden');$('noticeCancel').onclick=()=>$('noticeForm').classList.add('hidden');$('noticeSave').onclick=saveNotice;$('resetBtn').onclick=()=>{if(confirm('전체 데이터를 삭제할까요?')){records=[];saveAll();renderAll();}};document.querySelectorAll('.nav').forEach(b=>b.onclick=()=>view(b.dataset.view));document.querySelectorAll('[data-jump]').forEach(b=>b.onclick=()=>view(b.dataset.jump));});
